// Generated by CoffeeScript 1.6.3
(function() {
  var AI;

  AI = (function() {
    function AI() {}

    AI.prototype.getAiState = function(state) {
      var ab, cd, dead;
      ab = state.ableft - state.size;
      cd = state.cdleft - state.size;
      dead = state.score === 0;
      if (ab < 0) {
        return [cd, state.birdtop - state.abceiling, dead];
      }
      if (cd < 0) {
        return [ab, state.birdtop - state.cdceiling, dead];
      }
      if (ab < cd) {
        return [cd, state.birdtop - state.abceiling, dead];
      }
      return [ab, state.birdtop - state.cdceiling, dead];
    };

    AI.prototype.play = function(game, state) {
      var ai_state;
      this.game = game;
      this.state = state;
      if (Math.random() > 0.95) {
        this.game.jump();
      }
      ai_state = this.getAiState(this.state);
      return console.log(ai_state);
    };

    return AI;

  })();

  window.AI = new AI();

}).call(this);

/*
//@ sourceMappingURL=ai.map
*/
